#!/bin/ash

/bin/sh ./bin/kill_processes

date >> ./data/error.log

chmod 777 ./bin/Bake_Tobacco_Monitor
chmod 777 ./bin/download_fw
chmod 777 ./bin/version_parse

new_ver=`./bin/version_parse ./fws/fw_100/100.version`
res0=$?
cur_ver=`./bin/version_parse ./conf/version`
res1=$?

echo "new version is "$new_ver $res0
echo "cur version is "$cur_ver $res1

while true
do
	if [ $res0 != 0 ]
	then
		break
	fi

	if [ $res1 != 0 ]
	then
		break
	fi

	if [ "$new_ver" -gt "$cur_ver" ]
	then
		echo "update mid fw"
		
		cd ./fws/fw_100
		
		cp 100.$new_ver.fw 100.tar
		tar -xvf 100.tar
		rm 100.tar
		
		cd ./100
		/bin/sh update	
		
		cd ../../../
		
		echo '{"version":"'$new_ver'"}' > ./conf/version
		
		break
	else
		break
	fi

done

echo "start monitor"
./bin/Bake_Tobacco_Monitor &

sleep 5

/bin/sh ./bin/watchmen Bake_Tobacco_Monitor &
